### ISSUE TITLE
[1.10 - 1.6-Hotfix] Roots and ESM crash server

### ISSUE THREAD

**Issue by mrsmn** [whatthedrunk/allthemods#72]
Hi there,

Just letting you know as a heads up that installing [ESM ](http://minecraft.curseforge.com/projects/enhanced-server-moderation) makes roots-1.10.2-0.109/110.0 crash: http://pastebin.com/B01XQqHM.

[Apparently this has been fixed upstream and will be in the next release](https://github.com/elucent/Roots/issues/86).

Cheers.

**Comment by Carrots4U** [comment]
You mention it is fixed but in the issue thread I see you also mention it isn't. Mind clarifying? Thanks for taking your time to reporting the bug!

**Comment by mrsmn** [comment]
Well apparently this has bee fixed in the next roots release which is 1.10.2-0.111.0. I'll try it out as soon as the new version is out an let you both know.

**Comment by whatthedrunk** [comment]
Going to close this issue but please reopen it if it's still happening in 1.9 of the pack.

**Comment by mrsmn** [comment]
@whatthedrunk @Carrots4U Unfortunately still happening in v.1.9 of the pack:

http://pastebin.com/u97NFuvF

**Comment by mrsmn** [comment]
@whatthedrunk @Carrots4U roots has been [updated to v.1.10.2-0.111.0](https://minecraft.curseforge.com/projects/roots/files)
