### ISSUE TITLE
[1.10.7] Crash to desktop while leaving the Nether for the first time

### ISSUE THREAD

**Issue by DietmarKrause** [whatthedrunk/allthemods#95]
Issue Description:
crash log: http://pastebin.com/k7Pg5WzY
the portal was freshly build . Entering the Nether without problems, during leaving crash to desktop. Reentering world, found me stuck in earth in overworld. All materials lost no Gravestone to be found. Portal is free to enter from both sides. with one block space. 
Crash to Desktop while leaving th nether for the first time.
What happens:
Crash to desktop
What you expected to happen:
return to overworld
Steps to reproduce:

1. Start a new world
2. Build a nether portal 
3. go to nether
4. Leave Nether...
5. Crash to Dektop
Version of All the Mods:
1.10.2 v 1.9   
Added mods (Optifine, Fastcraft, etc.):

1. nothing added
2.
3.
 I had a copy of my safe folder and rebuild the Nether portal at a slightly different location and could reproduce the crash 3 times out of 10 trials (always reinstalling the copy new build of the portal , retry......). The location in the nether was always the same, It seems that the game do not always load the chunks in the overworld fast enough. Crash only at reentering the overworld never when entering the nether.  Notice to myself: Make a fresh copy of the world just before entering the nether every time....

**Comment by DietmarKrause** [comment]
i can profide you with a save of the world, if this helps. The world is not playable in the moment, for i get a crash almost evertime when returing out of the nether with the Description: Exception in server tick loop error. I see the overworldfor a short time when it is chunk loading, then crash.

**Comment by DnTheMn** [comment]
we have heard several people having this issue im not sure what to tell you.

**Comment by DietmarKrause** [comment]
thanks for the info. At least i am not the only one. Nether portal fix has had this issue in the past: https://minecraft.curseforge.com/projects/netherportalfix but the mod macker does not keep up an issue tracker, you can find it in the comments section of the mod only.

**Comment by DietmarKrause** [comment]
It is assigned as an issue in Journey Map https://bitbucket.org/TeamJM/journeymap/issues/101/server-occasionally-crashes-on-teleport. I found out that in the past it was already an issue there. It also happens from time to time for some users of the mod FTB unstable 1.10. so comparing the mods should lead to answers for not everything in identical.

**Comment by DietmarKrause** [comment]
i had a twitter discussion with Blay, the maker of Nether-Postal-fix, https://twitter.com/BlayTheNinth 
He says, his mod is not the cause, some other. Could not help futher.

**Comment by DietmarKrause** [comment]
issue is the same after recend update (v. 1.11). I started a new world and build a nether portal right at the beginning and everything seemed to be fine in this world until now.

**Comment by tivec** [comment]
For what it is worth, the bug still occurs on 1.12. I have tried removing mods, but I've been unable to find the cause.

**Comment by DietmarKrause** [comment]
i found an older post with the same issue in a different context. http://www.resonant-rise.com/topic/5331-first-crashes-from-nether-now-crash-on-world-load/
In that case CoFh fuxduct were the problem. You can see, that a single corrupt item/block in the world can leed to that isssue. In the new world of mine until now everything is fine. The difference is: in this new world i do not use mekansim at all. One has to find out what Block/item is causing the problem.

**Comment by jmcaffee** [comment]
I've received a ConcurrentModificationException crash on return from the nether twice now; once on v1.11 and once on v1.12.

**Comment by radiocrack** [comment]
I had this happen a few times as well.   I noticed some of the old mods and configs were sticking around when you keep updating the same profile.  

I fixed my problem by selecting "new profile" which installs a completely fresh client.  You have to manually copy over your mouse mappings and journey map to the new profile.

**Comment by DietmarKrause** [comment]
can you please tell me in more detail how to do this in the curse app? And what files do i have to copy to the new profile? I am not very familiar with this...

**Comment by jmcaffee** [comment]
I use MultiMC and completely replace my `config` and `mods` folders each update so there are other issues in play too.

**Comment by DietmarKrause** [comment]
that is important: i have not tried RF tools teleporters in this context beacuse it was early game in my SP world: You say there is no crash when teleporting instead of using the portal? That seems to be important for the cause of the issue. Second:  replacing the profile (like you did) does not solve the problem, as i understand you.

**Comment by jmcaffee** [comment]
MultiMC doesn't support the concept of a 'profile' so it doesn't relate other than to say: it also occurs without profile changes. 

It could be that Curse's concept/implementation of a profile (and its deletion) is the same thing as me blowing away the config/mods directories.

**Comment by radiocrack** [comment]
@DietmarKrause 
Not sure if you still want to know how to get a clean install and copy over your world.
 
In curse client instead of clicking play you can click versions you can pick the latest version to update to.  on the next screen if you select the option at the bottom that says "update to new profile" it will create a brand new instance of this pack.  No world. All changes you made are like starting over.
Your old world is still there in the previous version. 
Click back to the list of packs and you will see two instances of the pack.

If you want to copy your old world to the new instance open your original profile (where the play button is).  click the ellipses ( [...] ) at the top right. select "open folder".

Copy these files
Journeymap, saves, options.txt   (i think thats all you need)
Move up one directory to find the other instance (should have a (1) in the name)

If you do this then you effectively have a clean install of the pack. Also a backup of your world in the old instance.  Good idea to do this often or if you find an issue.  Try to repeat the issue with the latest version.

**Comment by DietmarKrause** [comment]
no change with the last build 1.13c: here is the fresh crashlog: http://pastebin.com/TU9ZjaDS. Leaving the nether with nether portal to the overworld leads to crash. Description: Exception in server tick loop

**Comment by DietmarKrause** [comment]
same problem with other pack, but he dig deeper: https://github.com/SleepyTrousers/EnderIO/issues/3626
somethin with elec core he said.

**Comment by ShaCraft** [comment]
I was the one testing on the above SleepyTrousers/EnderIO#3626. It can be done with either RFtools or Ender IO. if you remove both the crashes stop (on my test server). I think it may be Elecs as they both use that lib. I think I will opted to make RFtool "high tech nether portals"  (creative powered porters) on my new server to avoid the issue till the devs figure out who the issue truly belongs to and nail it down. 
I did not want to do with out either E/IO nor RFtools. 
Sha

**Comment by ZiggyAdventures** [comment]
Shacraft was right, caused by EnderCore old builds. Disabling EnderCore lets you play older worlds. Has been fixed for new worlds half a month ago.
